### ISSUE TITLE
Lambda environment variables parser/global data class initializer

### ISSUE THREAD

**Issue by ran-isenberg** [aws-powertools/powertools-lambda-python#1186] opened 2021-10-18 19:50 UTC
I think that this basic part of the lambda best practices is missing from the repo.
Validating environment variables, parsing them and saving them into an easy to reach singleton data class could be a very handy utility.
This is especially useful if you have multiple files in your lambda and you want an easy way to get an env variable (without having magic strings all over the code os.getenv('magic_string') etc.). 
You could call a get_env_vars() which will return a validated data class. 

For an example:
```
def handler(event, context):
# init env vars
conf = get_env_vars(MY_PYDANTIC_SCHEMA) # this will raise an exception in case of broken environment vars configuration

# init feature flags

# parse event input with powertools parser


if conf.magic_string: 
    # handle business logic
```

Implementation:
The easiest way to do this is to use Pydantic as it allows the user to parse according to schemas quite easily.
MY_PYDANTIC_SCHEMA in the example can look like this:
```
from pydantic import BaseModel, HttpURL
class MY_PYDANTIC_SCHEMA(BaseModel):
    env_var1: str
    env_var2: bool
    role_arn: str  # can add validations on ARN
   rest_api_endpoint: HttpURL
```

get_env_vars will init a global instance of MY_PYDANTIC_SCHEMA if it's None and return it. This will allow the easy use of parsed environment variables in any lambda file.
It also allows to transform any string based environment variables into a more complicated objects automatically.

I'd be happy to implement this. What do you think?

**Comment by leandrodamascena** [comment] 2023-09-05 17:50
Hi @ran-isenberg! I'm closing this issue as a duplicate of https://github.com/aws-powertools/powertools-lambda-python/issues/1172.

**Closed by leandrodamascena** 2023-09-05 17:50 UTC
Labels: duplicate, feature-request, need-rfc
